name: deploy document

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:


jobs:
  deploy-document:
    if: contains(github.event.head_commit.message, 'deploy') == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          git config --global user.email "junil.h@kakao.com"
          git config --global user.name "JunilHwang"

      - name: 배포
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          npm install -g yarn
          yarn install
          sh deploy-by-workflow.sh "deploy"
          
